# Generated by Django 4.1 on 2022-09-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votetitle',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
