# Generated by Django 4.1 on 2022-09-06 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_alter_votetitle_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote1', models.BooleanField(default=False, verbose_name='vote1')),
                ('vote2', models.BooleanField(default=False, verbose_name='vote1')),
                ('vote3', models.BooleanField(default=False, verbose_name='vote1')),
                ('votitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votetitle')),
            ],
        ),
    ]
