# Generated by Django 4.1 on 2022-09-06 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0003_voteform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(blank=True, default=True, max_length=100)),
                ('votitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.votetitle')),
            ],
        ),
        migrations.DeleteModel(
            name='VoteForm',
        ),
    ]
