# Generated by Django 4.1 on 2022-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0004_voting_delete_voteform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voting',
            old_name='choice',
            new_name='choice1',
        ),
        migrations.AddField(
            model_name='voting',
            name='choice2',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='voting',
            name='choice3',
            field=models.CharField(blank=True, default=True, max_length=100),
        ),
    ]
