# Generated by Django 4.1 on 2022-09-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0005_rename_choice_voting_choice1_voting_choice2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='votitle',
        ),
        migrations.AddField(
            model_name='voting',
            name='text',
            field=models.TextField(blank=True, default=True),
        ),
    ]
