# Generated by Django 4.1 on 2022-09-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0006_remove_voting_votitle_voting_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='choice1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='choice2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voting',
            name='choice3_count',
            field=models.IntegerField(default=0),
        ),
    ]
